### ISSUE TITLE
 ERROR [app 4/8] RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py

### ISSUE THREAD

**Issue by retivykh** [theirix/hilinkmon#1]
Tryed run command "docker-compose build" and got below error:

 => ERROR [app 4/8] RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py  0.7s
------
 > [app 4/8] RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -:
0.674   File "<stdin>", line 1
0.674     404: Not Found
0.674     ^
0.675 SyntaxError: illegal target for annotation
------
failed to solve: process "/bin/sh -c curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -" did not complete successfully: exit code: 1

**Comment by theirix** [comment]
Hello! Fixed this issue, please check out latest master
